version: "3.8"

services:
  voice-chat-platform:
    build: .
    container_name: voice-chat-platform
    ports:
      - "25812:25812"
    environment:
      - NODE_ENV=production
      - PORT=25812
      - UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=52428800
    volumes:
      - ./uploads:/app/uploads
      - ./conversations:/app/conversations
      - ./logs:/app/logs
      - ./config.json:/app/config.json
    restart: unless-stopped
    networks:
      - voice-chat-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:25812/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: voice-chat-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - voice-chat-platform
    restart: unless-stopped
    networks:
      - voice-chat-network

networks:
  voice-chat-network:
    driver: bridge

volumes:
  uploads:
  conversations:
  logs:
